only_rules:
  - identifier_name
  - empty_string
  - control_statement
  - colon
  - return_arrow_whitespace
  - syntactic_sugar
  - weak_delegate
  - yoda_condition
  - comma
  - leading_whitespace
  - let_var_whitespace
  - trailing_semicolon
  - opening_brace
  - empty_parentheses_with_trailing_closure
  - fallthrough
  - for_where
  - multiline_parameters
  - unused_optional_binding
  - unused_enumerated
  - unused_closure_parameter
  - unneeded_break_in_switch
  - unavailable_function
  - statement_position
  - large_tuple
  - type_name
  - force_unwrapping
  - force_cast
  - custom_rules

custom_rules:
  gesture_closure:
    included: ".*\\.swift"
    name: "Use weak self in gesture closures"
    message: "Use weak self when creating a gesture closure."
    regex: 'Gesture\s*\((\[\s*weak\s+self\s*\],.*)\)'
    severity: error

statement_position:
  severity: error

identifier_name:
  min_length:
    warning: 0
    error: 2
  max_length:
    warning: 999
    error: 50

type_name:
  min_length: 2
  max_length: 50

included:
  - TeamCreator

excluded: # paths to ignore during linting. Takes precedence over included.
  - Pods
  - R.generated.swift
  - Frameworks
  - Products
  - fastlane
  - guidelines
  - Derived
  - GamesApp/Libraries
  - Dangerfile.swift


